# Generated by Django 5.2.4 on 2025-08-23 18:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name="Elon bo'lim nomi")),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Elon nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasimi')),
                ('video', models.FileField(blank=True, help_text="Siz faqat 'mp4','avi','mov' video yuklay olasiz!", null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])], verbose_name='Videosi')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('published', models.BooleanField(default=True, help_text='Belgilasangiz saytga chiqadi!!!', verbose_name='Saytga chiqarilganmi?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.category', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['created'],
            },
        ),
    ]
