# Generated by Django 5.2.4 on 2025-08-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Oylik maosh'),
        ),
    ]
