# Generated by Django 5.2.4 on 2025-08-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancy_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=300, verbose_name='Oylik maosh'),
        ),
    ]
