# Generated by Django 5.2.4 on 2025-08-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(help_text='Masalan:500-600$/oy', max_length=50, verbose_name='Oylik maosh'),
        ),
    ]
