# Generated by Django 5.2.4 on 2025-08-24 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='phone',
            field=models.CharField(default='+998901234567', help_text='Masalan: +998901234567', max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998901234567 formatida bo'lishi kerak", regex='^\\+?\\d{9,15}$')], verbose_name='Telefon raqami'),
        ),
    ]
